---

language: node_js
before_install: sh scripts/travis-install.sh
before_script: sh scripts/travis-setup.sh
node_js:
- '0.10'

env:
    secure: "XcoNZObaenCa6E5z8KnCmmoz17nA0Ha5V3dMAr0K9Nb9G47ISyiNQF98UnPX\ny1k4F/yYE33wzOI9e2NXdHGSSd3px93KAwCsBiAEsoddJ4Wi5MBVb8e03SRc\nu9rT6L8lQxK+CeJJ4h/R96nhD3I/KvHQO0bk9w/jo9bq0LqloDg="
